version: '3.4'

services:
  poc.api.loadtest:
    image: ybustamante/fibonacciapi:latest
    build:
      context: .
      dockerfile: poc.api.loadtest/Dockerfile
    ports:
        - published: 8093
          target: 8093
  poc.api.nginxingress:
    image: ybustamante/fibonacciapiingress:latest
    build:
        context: .
        dockerfile: poc.api.loadtest/DockerfileIngress
    ports:
        - published: 7443
          target: 7443