version: '3.4'

services:
  poc.api.loadtest:
    image: ybustamante/fibonacciapi:latest
    build:
      context: .
      dockerfile: poc.api.loadtest/Dockerfile
    ports:
        - published: 9001
          target: 8090
  poc.api.nginxingress:
    image: ybustamante/fibonacciapiingess:latest
    build:
        context: .
        dockerfile: poc.api.loadtest/DockerfileIngress
    ports:
        - published: 443
          target: 8090
