kind: Deployment
apiVersion: apps/v1
metadata: 
  name: pocapifibonacci-deployment
  labels:
    k8s-app: fibonacciapi
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: fibonacciapi
  template:
    metadata:
      name: fibonacciapi
      labels:
        k8s-app: fibonacciapi
    spec:
      containers:
        - name: fibonacciapi
          image: ybustamante/fibonacciapi:latest
          ports:
            - containerPort: 40430
          resources:
            limits:
              memory: 129Mi
              cpu: "250m"