kind: Service
apiVersion: v1
metadata:
  name: pocapifibonacciservice  
  labels:
    k8s-app: fibonacciapi
spec:
  selector:     
    k8s-app: fibonacciapi
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  type: LoadBalancer
  sessionAffinity: None
  ipFamilies:
    - IPv4
  externalTrafficPolicy: Cluster

